version: 2
jobs:
  build:
    parallelism: 4
    branches:
      ignore:
        - gh-pages
    docker:
      - image: "circleci/node:8.7.0"
    environment:
      COVERALLS_REPO_TOKEN: 5VZxtP3jvfuAygXWjgkaJCrHpT9FwiVTU
    steps:
      - run:
          name: Installing global dependencies
          command: sudo npm install -g typescript rollup nyc coveralls
      - checkout
      - run:
          name: Installing PKI.js
          command: npm install
      - run:
          name: Installing node-webcrypto-ossl
          command: npm install node-webcrypto-ossl
      - run:
          name: Building tests
          command: npm run build:examples
      - run:
          name: Run tests (local)
          command: |
            TESTFILES=$(circleci tests glob "test/s_*.js" | circleci tests split --split-by=timings)
            npm run test_l -- ${TESTFILES}
      - run:
          name: Run tests (Node)
          command: npm run test_l -- "test/n_*.js"
      - run:
          name: Coveralls
          command: cat ./coverage/lcov.info | coveralls
      - store_artifacts:
          path: ./coverage/lcov.info
          destination: coverage
