version: 2

jobs:
  installation:
    working_directory: ~/pkijs
    docker:
      - image: "circleci/node:8.7.0"
    environment:
      COVERALLS_REPO_TOKEN: 5VZxtP3jvfuAygXWjgkaJCrHpT9FwiVTU
    steps:
      - run:
          name: Installing global dependencies
          command: sudo npm install -g typescript
      - checkout
      - run:
          name: Installing PKI.js
          command: npm install
      - run:
          name: Installing node-webcrypto-ossl
          command: npm install node-webcrypto-ossl
      - run:
          name: Building tests
          command: npm run build:examples
      - save_cache:
          key: -{{ .Branch }}-{{ .Revision }}
          paths:
            - ~/pkijs

  test1:
    parallelism: 4
    working_directory: ~/pkijs
    docker:
      - image: "circleci/node:8.7.0"
    steps:
      - restore_cache:
          key: -{{ .Branch }}-{{ .Revision }}
      - run: npm run test:node

  test2:
    working_directory: ~/pkijs
    docker:
      - image: "circleci/node:8.7.0"
    steps:
      - checkout
      - attach_workspace:
          at: ~/pkijs
      - restore_cache:
          key: -{{ .Branch }}-{{ .Revision }}
      - run: ls -al

workflows:
  version: 2
  main:
    jobs:
      - installation:
          filters:
            branches:
              ignore:
                - gh-pages
      - test1:
          requires:
            - installation
      - test2:
          requires:
            - installation