version: 2
jobs:
  build:
    branches:
      ignore:
        - gh-pages
    machine: true
    environment:
      COVERALLS_REPO_TOKEN: 5VZxtP3jvfuAygXWjgkaJCrHpT9FwiVTU
    steps:
      - run:
          name: Install Node.js
          command: |
            curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
            sudo apt-get install -y nodejs
      - run:
          name: Install NPM
          command: sudo apt install npm
      - run:
          name: Installing global dependencies
          command: npm install -g typescript rollup nyc coveralls
      - checkout
      - run:
          name: Installing PKI.js
          command: npm install
      - run:
          name: Installing node-webcrypto-ossl
          command: npm install node-webcrypto-ossl
      - run:
          name: Building tests
          command: npm run build:examples
      - run:
          name: Run tests
          command: npm run test:node
      - run:
          name: Coveralls
          command: cat ./coverage/lcov.info | coveralls
      - store_artifacts:
          path: ./coverage/lcov.info
          destination: coverage
